### PR TITLE
update abstract-leveldown

### PR DESCRIPTION
**Pull request by ralphtheninja**
I adjusted tests for default options in `.get()` which no longer is an empty object.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Perhaps we should update to `~2.1.0` instead?

/cc @rvagg

**Comment by ralphtheninja** [comment]
https://github.com/rvagg/node-leveldown/pull/143

**Comment by rvagg** [comment]
+1

**Comment by ralphtheninja** [comment]
:+1:

**Comment by ralphtheninja** [comment]
```
$ npm publish
+ deferred-leveldown@1.0.0
```

**Pull request merged**
