### PR TITLE
tweak badges

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by vweevers** [comment]
Maybe move the npm version badge to be the second badge.

**Comment by ralphtheninja** [comment]
When we are happy with the order we can just take that as a template for all the other modules. They should look rather similar with some exceptions for e.g. `leveldown` and `memdown` etc.

**Comment by vweevers** [comment]
Regarding the level badge: how is the website set up? If we add an SVG to [assets/static/img](https://github.com/Level/leveldb.org/tree/master/assets/static/img), does it automatically go live? Would be nice to have a simple SVG url to include everywhere.

**Comment by ralphtheninja** [comment]
> Regarding the level badge: how is the website set up? If we add an SVG to assets/static/img, does it automatically go live? Would be nice to have a simple SVG url to include everywhere.

I'm not sure if it will automatically go live. It's @0x00A that has access to it. Would definitely be nice with a hosted url.

cc @juliangruber

**Comment by ralphtheninja** [comment]
> If we add an SVG to assets/static/img, does it automatically go live?

Lets try it? :)

**Comment by vweevers** [comment]
Hmm if I save the SVG, the logo is still embedded (`<image xlink:href="data:image/svg+xml;base64,..`) rather than inlined. I don't know SVG that well, can we / should we fix this?

**Comment by vweevers** [comment]
Sorry for this side-quest ;)

**Comment by vweevers** [comment]
Or replace it with: `<image x="5" y="3" width="14" height="14" xlink:href="http://leveldb.org/img/logo.svg"/>`

Seems to work; don't know whats best.

**Comment by vweevers** [comment]
> If we add an SVG to assets/static/img, does it automatically go live?

Oh it's as simple as [`npm run deploy`](https://github.com/Level/leveldb.org#for-maintainers).

**Comment by ralphtheninja** [comment]
@vweevers Let me know if I should update something in this PR.

**Comment by vweevers** [comment]
@ralphtheninja new badge URL: http://leveldb.org/img/badge.svg

**Comment by ralphtheninja** [comment]
Side note: We should really have https for leveldb.org

**Comment by ralphtheninja** [comment]
2.0.2

**Pull request merged**
